addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - "2.7"

env:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"
# either use the two lines above or the two below. Don't change the default if
# it's not necessary (it is only necessary if modules in your repository can't
# be installed in the same database. And you get a huge speed penalty in your
# tests)
#  - VERSION="8.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1" LINT_CHECK="0"
#  - VERSION="8.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/OCA/account-financial-tools.git ${HOME}/account-financial-tools
  - git clone https://github.com/OCA/bank-payment.git ${HOME}/bank-payment
  - git clone https://github.com/aeroo/aeroo_reports.git ${HOME}/aeroo_reports
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - sudo pip install unidecode
  - travis_install_nightly
  - git clone https://github.com/aeroo/aeroolib.git ${HOME}/aeroolib
  - pushd ${HOME}/aeroolib; sudo python ./setup.py install; popd
  - sudo apt-get install python-cups

script:
  - travis_run_tests

after_success:
  coveralls
